### ISSUE TITLE
[Question] - Do we have to enable a settings in the iOS App ID Settings

### ISSUE THREAD

**Issue by fpoirier1** [255kb/cordova-plugin-bluetooth-status#1]
Is there anything we need to activate (see image below) so my app can access the Bluetooth of the device?

<img width="695" alt="screen shot 2015-09-02 at 11 08 07 am" src="https://cloud.githubusercontent.com/assets/1587658/9635168/0cf79282-5163-11e5-9591-53b4e86da5f7.png">

**Comment by 255kb** [comment]
There is nothing to add in the Xcode project. 
In iOS permission will be asked to the user through a popup at the time you check the bluetooth state (as for any other iOS permission).
For Android, the plugin automatically adds the needed permissions (`android.permission.BLUETOOTH` and `android.permission.BLUETOOTH_ADMIN`).

**Comment by fpoirier1** [comment]
Merci !

**Comment by 255kb** [comment]
pas de problème ;)
