### ISSUE TITLE
Add ability to disable on Android.

### ISSUE THREAD

**Issue by RangerMauve** [255kb/cordova-plugin-bluetooth-status#5]
It seems that there's a [parallel](http://stackoverflow.com/a/20142972/994684) to the `enable()` method in `BluetoothAdapter` called `disable()`. It'd be nice if this plugin exposed it as a method.

**Comment by 255kb** [comment]
Thanks, good to know, I will see to integrate this method in the next version.

**Comment by 255kb** [comment]
Sorry but this package is not maintained anymore, and I won't be fixing any bugs or adding new features
